### ISSUE TITLE
Errors on MacOSx

### ISSUE THREAD

**Issue by antani** [aam1r/sachet#12]
$ vim
Error detected while processing /Users/vantani/.vimrc:
line    4:
E117: Unknown function: pathogen#infect
line    5:
E117: Unknown function: pathogen#helptags
..after the vim is opened...
Error detected while processing VimEnter Auto commands for "*":
E492: Not an editor command: NERDTree
Press ENTER or type command to continue

**Comment by antani** [comment]
this is on iterm and MacOSX

**Comment by aam1r** [comment]
Another user sent me screenshots (attached) of this happening to them. Not sure why this is happening. 
![Screen Shot 2013-03-08 at 4 38 54 PM](https://f.cloud.github.com/assets/566418/240291/80e2fd8c-8904-11e2-98a6-18dc54cf5f21.png)
![Screen Shot 2013-03-08 at 4 39 05 PM](https://f.cloud.github.com/assets/566418/240292/80f3674e-8904-11e2-831b-ecb2e4638d00.png)

What version of vim are you running? Can you paste your output of "vim --version"?

**Comment by cnu** [comment]
I get the same error on Mac 10.8.2 VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Jun 20 2012 13:16:02).

I tried it in both Terminal and iTerm.

**Comment by aam1r** [comment]
@cnu, thanks for reporting. Could you upload your .vimrc to http://gist.github.com and paste the link?

**Comment by cnu** [comment]
https://gist.github.com/cnu/5126894
Has both the vimrc and the error I get.

**Comment by cnu** [comment]
Nope, Changing call to execute doesn't fix it.

Now I get an `Invalid expression:` error after the `Unknown Function` error.

**Comment by jamesaanderson** [comment]
Can you try https://gist.github.com/jamesaanderson/5126978

**Comment by cnu** [comment]
No luck, Getting the same error. Infact I tried out `filetype off` even before you posted this.

**Comment by jamesaanderson** [comment]
I just installed sachet successfully on Mountain Lion. Just make sure to copy vimrc to ~/.vimrc and copy vim to ~/.vim and remove any previous vimrc files or your vim directory.

**Comment by cnu** [comment]
Hmm, that is weird. I rm'ed the files and folders and again copied them back. It worked now. 
Previously there were no .vimrc file but there was a .vim folder. 

I guess copying to the default .vim folder doesn't work. 

Great project btw.

**Comment by antani** [comment]
This happens when directory - vim is not copied correctly in the home
directory. I had it copied as /
Users/ved/.vim/vim - this obviously did not work

sent from unpretentious mobile, pardon brevity and big thumbs

**Comment by aam1r** [comment]
@antani That probably explains why. I think the instructions need to be made much more clear on how the files should be copied.

**Comment by antani** [comment]
Also it would help if you document how to change themes, etc
Thanks - awesome work for us vim lovers

Thanks,

Ved
http://about.me/ved

**Comment by jamesaanderson** [comment]
It might be helpful to add an install.sh or rake task to move the vimrc and vim directory.

**Comment by aam1r** [comment]
@jamesaanderson I think having an install.sh will be a good idea. My only concern is that I am not sure how that will work out on Windows (27.8% of users who have downloaded sachets are running Windows)

**Comment by aam1r** [comment]
I have added an `install.sh` script that does the copying process for the user. Hopefully that should reduce the number of people facing this issue.
