### ISSUE TITLE
Save backup of .vimrc file and .vim dir before installing

### ISSUE THREAD

**Issue by ivanistheone** [aam1r/sachet#17]
I wish I could go back to my old settings now that I have tried sachet...

**Comment by jamesaanderson** [comment]
I'm guessing you used the install.sh. Am I right?

**Comment by ivanistheone** [comment]
> I'm guessing you used the install.sh. Am I right?

Yep. Actually, I looked at the script and made a backup
of the file and the dir before I installed so I am OK, but if
you are feeling guilty then u should fix it ;)

say,

cp ~/.vimrc ~/Desktop/my_pld_vimrc_file
cp -r ~/.vim ~/Desktop/my_pld_vim_dir

ivan

**Comment by aam1r** [comment]
Sounds like a good feature to have. I will add this soon!
