### ISSUE TITLE
Cursor default to text window and not NERDTree

### ISSUE THREAD

**Issue by FabianN** [aam1r/sachet#18]
Thanks for the config, but I've got one issue. I love NERDTree now that I've found it, but I do not like that the cursor defaults to the NERDTree pane. I'm new to vim config editing, is there a way where I can have the other pane be selected by default and not the NERDTree pane?

**Comment by aam1r** [comment]
Going to look into it. Thanks for bringing this up!

**Comment by jamesaanderson** [comment]
@aam1r 

```
autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p
```

Ok if I open a pull request?

**Comment by FabianN** [comment]
@jamesaanderson 
Sweet! Thank you for that.

**Comment by aam1r** [comment]
Thank you @jamesaanderson. Pull request merged and deployed to yoursachet.com.
