### ISSUE TITLE
nocompatible should either be omitted from vimrc or first

### ISSUE THREAD

**Issue by idbrii** [aam1r/sachet#2]
`:help compatible`:

>   If you set this option in your vimrc file, you should probably put it at the very start.
> When a |vimrc| or |gvimrc| file is found while Vim is starting up, this option is switched off

Anything set by pathogen could be cleared by `nocp`. It should either be the first thing in the vimrc or omitted entirely (since it's redundant).

I generated a vimrc that started thus:

```
" Pathogen
call pathogen#infect()
call pathogen#helptags()

set nocompatible
set statusline=%<\ %n:%f\ %m%r%y%=%-35.(line:\ %l\ of\ %L,\ col:\ %c%V\ (%P)%)
filetype plugin indent on
```

**Comment by aam1r** [comment]
Good point. Thanks for pointing this out!
