### ISSUE TITLE
Problem with install.sh

### ISSUE THREAD

**Issue by kelto** [aam1r/sachet#25]
Hi !

I think there might be a problem with the install.sh
When I install it, it put everyfile in a vim directory, so ~/.vim/vim/*
Which cause some problem on my linux distribution (Fedora 20). 
Just need a "cp -R ~/.vim/vim/\* ~/.vim/" to fix it though.

I'm using Fedora 20 and Vim 7.4 if it can help

**Comment by aam1r** [comment]
@kelto, thanks for reporting! I would be happy to accept the Pull Request if you could push a fix :smile:

**Comment by aam1r** [comment]
I believe this has been fixed in #28. Feel free to reopen if the issue persists.
