### ISSUE TITLE
Don't modify rtp if pathogen is doing it

### ISSUE THREAD

**Issue by idbrii** [aam1r/sachet#3]
I generated a setup with ctrlp and the vimrc had:

```
" ctrlp
set runtimepath^=~/.vim/bundle/ctrlp.vim
```

But it also has pathogen. Why not just let pathogen handle the `runtimepath`?

**Comment by aam1r** [comment]
Thanks for pointing this out. Removed the redundant statement (+ fixed some whitespace issues).
